services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/smartAuthentication
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=9042
      - SUPPORT_EMAIL=nshuti.fabrice09@gmail.com
      - APP_PASSWORD=klsamimzojenzgra
    depends_on:
      - postgres
    networks:
      - spring-project

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_DB=smartAuthentication
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-project

volumes:
  postgres-data:

networks:
  spring-project: